IRB web application/Models/AdminHomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IRB_web_application.Models
{
    public class AdminHomeViewModel
    {
        public string NumberOfInstitution { get; set; }
        public string NumberOfUsers { get; set; }

    }

    
}

IRB web application/Models/FacultyHomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IRB_web_application.Models
{
    public class FacultyHomeViewModel
    {
        public string NumberOFApplications { get; set; }
        public string NumberOfSubmittedApplications { get; set; }
        public string NumberOfPendingApplications { get; set; }
    }
}

IRB web application/Models/StaffHomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IRB_web_application.Models
{
    public class StaffHomeViewModel
    {
        public string NumberOFApplications { get; set; }
        public string NumberOfSubmittedApplications { get; set; }
        public string NumberOfPendingApplications { get; set; }
    }
}

IRB web application/Controllers/HomeController.cs
using IRB_web_application.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IRB_web_application.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationUserManager _userManager;
        ApplicationDbContext context = new ApplicationDbContext();
        UserDBRepository users = new UserDBRepository();

        public HomeController(ApplicationUserManager userManager)
        {                                                                     
            UserManager = userManager;
        }

        public HomeController()
        {
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                if (!isAdminApproved())
                {
                    return RedirectToAction("NotConfirmed", "Account");
                }
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        public PartialViewResult SuperAdminHome()
        {
            AdminHomeViewModel adminHome = new AdminHomeViewModel();
            var NumberofUni = context.universities.Select(c => c.ID).ToList();        
            int countUni = NumberofUni.Count();//Here you will  get count
            adminHome.NumberOfInstitution = countUni.ToString();

            var NumberofUsers = context.Users.Select(c => c.Id).ToList();
            int countUsers = NumberofUsers.Count();//Here you will  get count
            adminHome.NumberOfUsers = countUsers.ToString();
            return PartialView(adminHome);
        }

        public PartialViewResult StudentHome()
        {
            StudentHomeModel studentHome = new StudentHomeModel();
            studentHome.NumberOFApplications = "12";
            studentHome.NumberOfPendingApplications = "3";
            studentHome.NumberOfSubmittedApplications = "24";

            return PartialView(studentHome);
        }

        public PartialViewResult FacultyHome()
        {
            FacultyHomeViewModel facultytHome = new FacultyHomeViewModel();
            facultytHome.NumberOFApplications = "12";
            facultytHome.NumberOfPendingApplications = "3";
            facultytHome.NumberOfSubmittedApplications = "24";

            return PartialView(facultytHome);
        }

        public PartialViewResult StaffHome()
        {
            StaffHomeViewModel staffHome = new StaffHomeViewModel();
            staffHome.NumberOFApplications = "12";
            staffHome.NumberOfPendingApplications = "3";
            staffHome.NumberOfSubmittedApplications = "24";

            return PartialView(staffHome);
        }

        public PartialViewResult IRBMemberHome()
        {
            IRBMemberViewModel IRBMemberHome = new IRBMemberViewModel();
            IRBMemberHome.NumberOFApplications = "12";
            IRBMemberHome.NumberOfPendingApplications = "3";
            IRBMemberHome.NumberOfSubmittedApplications = "24";

            return PartialView(IRBMemberHome);
        }


        public PartialViewResult AdminHome()
        {
            AdminHomeViewModel UniadminHome = new AdminHomeViewModel();

            if (User.Identity.IsAuthenticated)
            {

                var Admin = User.Identity;
                var AdminID = Admin.GetUserId();
                var AdminUSer = context.Users.Find(AdminID);
                var NumberofUsers = users.GetUsersByUnversityID(AdminUSer.UniversityID);
                Session["UniversityID"] = AdminUSer.UniversityID;
                int countUsers = NumberofUsers.Count();//Here you will  get count
                UniadminHome.NumberOfUsers = countUsers.ToString();
            }
           
            return PartialView(UniadminHome);
        }
        public FileContentResult UserPhotos()
        {
            if (User.Identity.IsAuthenticated)
            {
                String userId = User.Identity.GetUserId();
                // to get the user details to load user Image
                var bdUsers = HttpContext.GetOwinContext().Get<ApplicationDbContext>();

                var userImage = bdUsers.Users.Where(x => x.Id == userId).FirstOrDefault();

                if (userId == null || userImage == null)
                {
                    string fileName = HttpContext.Server.MapPath(@"~/Images/noImg.png");

                    byte[] imageData = null;
                    FileInfo fileInfo = new FileInfo(fileName);
                    long imageFileLength = fileInfo.Length;
                    FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                    BinaryReader br = new BinaryReader(fs);
                    imageData = br.ReadBytes((int)imageFileLength);
                    

                    return File(imageData, "image/png");

                }
                

                return new FileContentResult(userImage.UserPhoto, "image/jpeg");
            }
            else
            {
                string fileName = HttpContext.Server.MapPath(@"~/Images/noImg.png");

                byte[] imageData = null;
                FileInfo fileInfo = new FileInfo(fileName);
                long imageFileLength = fileInfo.Length;
                FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                BinaryReader br = new BinaryReader(fs);
                imageData = br.ReadBytes((int)imageFileLength);
                return File(imageData, "image/png");

            }
        }

        public ActionResult About()
        {
            if (!isAdminApproved())
            {
                return RedirectToAction("NotConfirmed", "Account");
            }
            
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            if (!isAdminApproved())
            {
                return RedirectToAction("NotConfirmed", "Account");
            }
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public bool isAdminApproved()
        {
            bool t = false;
            try
            {
                var user = User.Identity;
                var presentUser = context.Users.Find(user.GetUserId());
               
                if (presentUser.AdminApproved)
                    return t = presentUser.AdminApproved;
                else
                    return t = false;
            }
            catch(Exception e)
            {
                
            }
            return t;
        }

        // send Email message
        public async Task sendEmail(string to, string body, string Subject)
        {
            GMailer mailer = new GMailer
            {
                ToEmail = to,
                Subject = Subject,
                Body = body,
                IsHtml = true
            };
            await mailer.Send();
        }
    }
}

IRB web application/Controllers/RoleController.cs
using IRB_web_application.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IRB_web_application.Controllers
{
    public class RoleController : Controller
    {
        // GET: RoleViewModel
        ApplicationDbContext context;

        public RoleController()
        {
            context = new ApplicationDbContext(); 
        }
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {


                if (!isSuperAdminUser())
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            var Roles = context.Roles.ToList();
            return View(Roles);
        }
       

        public Boolean isSuperAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());
                if (s[0].ToString() == "SuperAdmin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }
    }
}

IRB web application/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

IRB web application/Views/Home/AdminHome.cshtml
@model IRB_web_application.Models.AdminHomeViewModel

<ul class="nav nav-pills">

    <li class="active"><a href="#">Home</a></li>
    <li><a href="#">Menu 1</a></li>
    <li><a href="#">Menu 2</a></li>
    <li><a href="#">Menu 3</a></li>
</ul>
<br />
<h2>Admin Home</h2>
<div class="row">
   
    <div class="col-md-4">
        <h2>Manage Users: @Model.NumberOfUsers</h2>
        <p> @Html.ActionLink("View Users", "Index", "Users", null, new { })</p>
    </div>
    <div class="col-md-4">
        <h2>Manage University</h2>
        <p>Coming soon!</p>
    </div>
</div>

IRB web application/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

IRB web application/Views/Home/FacultyHome.cshtml
@model IRB_web_application.Models.FacultyHomeViewModel

<div>
    <h2>Student Dashboard</h2>
    <div class="row">

        <div class="col-lg-4 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3>@Model.NumberOFApplications</h3>

                    <p>Manage Applications</p>
                </div>
                <div class="icon">
                    <i class="fa fa-pencil"></i>
                </div>
                <p class="small-box-footer">@Html.ActionLink("Manage Applications", "Index", "Application")&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></p>
            </div>
        </div>

        <div class="col-lg-4 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3>@Model.NumberOFApplications</h3>

                    <p>Manage Collaborative Applications</p>
                </div>
                <div class="icon">
                    <i class="fa fa-pencil"></i>
                </div>
                <p class="small-box-footer">@Html.ActionLink("Manage Collaborative Applications", "Index", "CollaborativeUsersManagement")&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></p>
            </div>
        </div>

        <div class="col-lg-4 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3>@Model.NumberOFApplications</h3>

                    <p>Faculty Hub</p>
                </div>
                <div class="icon">
                    <i class="fa fa-pencil"></i>
                </div>
                <p class="small-box-footer">@Html.ActionLink("Faculty Sponsorship", "Index", "FacultyHub")&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></p>
            </div>
        </div>


    </div>
</div>
<br />

IRB web application/Views/Home/IRBMemberHome.cshtml
@model IRB_web_application.Models.IRBMemberViewModel


<br />
<h2>IRB Member Dashboard</h2>
<div class="row">

    <div class="col-lg-4 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>@Model.NumberOFApplications</h3>

                <p>Manage Applications</p>
            </div>
            <div class="icon">
                <i class="fa fa-pencil"></i>
            </div>
            <p class="small-box-footer">@Html.ActionLink("Manage Applications", "Index", "Application")&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></p>
        </div>
    </div>


    <div class="col-lg-4 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>2</h3>

                <p>Manage IRB</p>
            </div>
            <div class="icon">
                <i class="fa fa-pencil"></i>
            </div>
            <p class="small-box-footer"> @Html.ActionLink("Manage IRB", "Index", "IRBManagement", null, new { })&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></p>
        </div>
    </div>


   

</div>

IRB web application/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<div class="row">
    @if (User.Identity.IsAuthenticated)
    {
        if (User.IsInRole("SuperAdmin"))
        {
            Html.RenderAction("SuperAdminHome", "Home");
        } else  
        if (User.IsInRole("Admin"))
        {
            Html.RenderAction("AdminHome", "Home");
        }else  if (User.IsInRole("Student"))
        {
            Html.RenderAction("StudentHome", "Home");
        }else  if (User.IsInRole("IRB Member"))
        {
            Html.RenderAction("IRBMemberHome", "Home");
        }else  if (User.IsInRole("Faculty"))
        {
            Html.RenderAction("FacultyHome", "Home");
        }else  if (User.IsInRole("Staff"))
        {
            Html.RenderAction("StaffHome", "Home");
        }
    }
</div>

IRB web application/Views/Home/StaffHome.cshtml
@model IRB_web_application.Models.StaffHomeViewModel

<div>
    <h2>Student Dashboard</h2>
    <div class="row">

        <div class="col-lg-4 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3>@Model.NumberOFApplications</h3>

                    <p>Manage Applications</p>
                </div>
                <div class="icon">
                    <i class="fa fa-pencil"></i>
                </div>
                <p class="small-box-footer">@Html.ActionLink("Manage Applications", "Index", "Application")&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></p>
            </div>
        </div>

        <div class="col-lg-4 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3>@Model.NumberOFApplications</h3>

                    <p>Manage Applications</p>
                </div>
                <div class="icon">
                    <i class="fa fa-pencil"></i>
                </div>
                <p class="small-box-footer">@Html.ActionLink("Manage Collaborative Applications", "Index", "CollaborativeUsersManagement")&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></p>
            </div>
        </div>


    </div>
</div>
<br />

IRB web application/Views/Home/StudentHome.cshtml
@model IRB_web_application.Models.StudentHomeModel

    <div>
        <h2>Student Dashboard</h2>
        <div class="row">

            <div class="col-lg-4 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3>@Model.NumberOFApplications</h3>

                        <p>Manage Applications</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-pencil"></i>
                    </div>
                    <p class="small-box-footer">@Html.ActionLink("Manage Applications", "Index", "Application")&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></p>
                </div>
            </div>

            <div class="col-lg-4 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3>@Model.NumberOFApplications</h3>

                        <p>Manage Applications</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-pencil"></i>
                    </div>
                    <p class="small-box-footer">@Html.ActionLink("Manage Collaborative Applications", "Index", "CollaborativeUsersManagement")&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></p>
                </div>
            </div>


        </div>
    </div>
<br />

IRB web application/Views/Home/SuperAdminHome.cshtml
@model IRB_web_application.Models.AdminHomeViewModel
<div>
    <h2>SuperAdmin Dashboard</h2>
    <div class="row">
       
        <div class="col-lg-4 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3>4</h3>

                    <p>Manage the User Roles</p>
                </div>
                <div class="icon">
                    <i class="fa fa-user"></i>
                </div>
                <p class="small-box-footer">@Html.ActionLink("Manage Role", "Index", "Role")&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></p>
            </div>
        </div>
        <div class="col-lg-4 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-yellow">
                <div class="inner">
                    <h3>@Model.NumberOfUsers</h3>

                    <p>Number of Users</p>
                </div>
                <div class="icon">
                    <i class="fa fa-group"></i>
                </div>
                <p class="small-box-footer"> @Html.ActionLink("Manage Users", "SuperAdminList", "Users")&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></p>
            </div>
        </div>

        <div class="col-lg-4 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-green">
                <div class="inner">
                    <h3> @Model.NumberOfInstitution</h3>

                    <p>Number of Institution</p>
                </div>
                <div class="icon">
                    <i class="fa fa-university"></i>
                </div>
                <p class="small-box-footer"> @Html.ActionLink("Manage Universities ", "Index", "universities")&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></p>
            </div>
        </div>
       
    </div>
</div>