IRB web application/Controllers/IRBManagementController.cs
using IRB_web_application.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IRB_web_application.Controllers
{
    public class IRBManagementController : Controller
    {

        ApplicationDbContext context;
        private ApplicationUserManager _userManager;

        public IRBManagementController()
        {
            context = new ApplicationDbContext();
        }

        public IRBManagementController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: IRBManagement
        public ActionResult Index()
        {
            var user = User.Identity;
            ApplicationUser presentUser = context.Users.Find(user.GetUserId());

            return View(presentUser);
        }

        public ActionResult ListIRBMembers()
        {
            var user = User.Identity;
            ApplicationUser presentUser = context.Users.Find(user.GetUserId());
            var UniversityID = presentUser.UniversityID;
            UserDBRepository Members = new UserDBRepository();

            return View(Members.GetAllIRBMembers(UniversityID));
        }

        public ActionResult Details(string Id)
        {
            ApplicationUser IRBMember = context.Users.Find(Id);
            return View(IRBMember);
        }

        public ActionResult ListAssignedApplications(string Id)
        {
            var IRBMember = context.Users.Find(Id);
            string IRBMemberEmail = IRBMember.Email;
            ApplicationBasicDetail applicationBasicDetail = new ApplicationBasicDetail();
            var ListApplications = applicationBasicDetail.GetApplicationListByAssignedStaff(IRBMemberEmail);
            return View(ListApplications);
        }

        public ActionResult IRBApplicationsAssignedOrUndecided()
        {
            var user = User.Identity;
            ApplicationUser presentUser = context.Users.Find(user.GetUserId());
            var UniversityID = presentUser.UniversityID;
            ApplicationBasicDetail applicationBasicDetail = new ApplicationBasicDetail();
            var ListApplications = applicationBasicDetail.GetListOFApplicationsByUniversityAndApplicationState(UniversityID, "Assigned");
            return View(ListApplications);
        }

        public ActionResult IRBSumbittedApplication()
        {
            var user = User.Identity;
            ApplicationUser presentUser = context.Users.Find(user.GetUserId());
            var UniversityID = presentUser.UniversityID;
            ApplicationBasicDetail Application = new ApplicationBasicDetail();
            List<ApplicationBasicDetail> ApplicationList = new List<ApplicationBasicDetail>();
            ApplicationList = Application.GetListOFNonStandardApplicationsByUniversityAndApplicationState(UniversityID, "Submitted");

            return View(ApplicationList);
        }

        public ActionResult AssignApplication(string Id)
        {
            Session["AssignAppID"] = Id;
            var user = User.Identity;
            ApplicationUser presentUser = context.Users.Find(user.GetUserId());
            var UniversityID = presentUser.UniversityID;
            ApplicationBasicDetail applicationBasicDetail = new ApplicationBasicDetail();
            applicationBasicDetail = context.ApplicationBasicDetails.Find(Id);

            UserDBRepository ListMembers = new UserDBRepository();
            ViewBag.Name = new SelectList(ListMembers.GetAllIRBMemberEmailAddress(UniversityID));
            return View(applicationBasicDetail);
        }

        [HttpPost]
        public ActionResult AssignToStaff(string Name)
        {

            var Id = Session["AssignAppID"].ToString();
            var user = User.Identity;
            ApplicationUser presentUser = context.Users.Find(user.GetUserId());
            var UniversityID = presentUser.UniversityID;
            UserDBRepository ListMembers = new UserDBRepository();
            ViewBag.Name = new SelectList(ListMembers.GetAllIRBMemberEmailAddress(UniversityID));

            ApplicationBasicDetail applicationBasicDetail = new ApplicationBasicDetail();
            applicationBasicDetail = context.ApplicationBasicDetails.Find(Id);
            applicationBasicDetail.AssignedStaff = Name;
            applicationBasicDetail.ApplicationState = "Assigned";
            applicationBasicDetail.DateStateUpdate = DateTime.Now;
            context.Entry(applicationBasicDetail).State = System.Data.Entity.EntityState.Modified;
            context.SaveChanges();

            return RedirectToAction("IRBSumbittedApplication");
        }

        public ActionResult ListAllApplications()
        {
            var user = User.Identity;
            ApplicationUser presentUser = context.Users.Find(user.GetUserId());
            var UniversityID = presentUser.UniversityID;
            ApplicationBasicDetail applicationBasicDetail = new ApplicationBasicDetail();
            var ListApplications = applicationBasicDetail.GetListOFSubmittedApplicationsByUniversity(UniversityID);
            return View(ListApplications);
        }

        public ActionResult ListIRBStandardApplication()
        {
            var user = User.Identity;
            ApplicationUser presentUser = context.Users.Find(user.GetUserId());
            var UniversityID = presentUser.UniversityID;
            ApplicationBasicDetail applicationBasicDetail = new ApplicationBasicDetail();
            var ListApplications = applicationBasicDetail.GetListOFStandardApplicationsByUniversityAndApplicationState(UniversityID, "Submitted");
            return View(ListApplications);
        }


        public ActionResult ListApplicationsAssignedToMember()
        {
            
            ViewBag.State = new SelectList(new List<string> { "Assigned", "Approved", "Rejected", "Approved by Condition", "Reassigned"});
            var user = User.Identity;
            ApplicationUser presentUser = context.Users.Find(user.GetUserId());
            var UserEmail = presentUser.Email;
            ApplicationBasicDetail applicationBasicDetail = new ApplicationBasicDetail();
            var ListApplications = applicationBasicDetail.GetApplicationListByAssignedStaffandState(UserEmail, "Assigned");
            return View(ListApplications);
        }

        [HttpPost]
        public ActionResult ListApplicationsAssignedToMember(string State)
        {
           if(State == "")
            {
                return RedirectToAction("ListApplicationsAssignedToMember");
            }
            ViewBag.State = new SelectList(new List<string> { "Assigned", "Approved", "Rejected", "Approved by Condition", "Reassigned" });
            var user = User.Identity;
            ApplicationUser presentUser = context.Users.Find(user.GetUserId());
            var UserEmail = presentUser.Email;
            ApplicationBasicDetail applicationBasicDetail = new ApplicationBasicDetail();
            var ListApplications = applicationBasicDetail.GetApplicationListByAssignedStaffandState(UserEmail, State);
            return View(ListApplications);
        }


        public ActionResult Preview(string id)
        {
            string ApplicationID = id;
            if (id == null)
                ApplicationID = Session["ApplicationID"].ToString();

            ApplicationBasicDetail applicationBasicDetail = new ApplicationBasicDetail();
            var PI = applicationBasicDetail.GetPrincipalInvestigator(ApplicationID);
            ApplicationViewModel viewModel = new ApplicationViewModel
            {
                ApplicationBasicDetail = context.ApplicationBasicDetails.Find(ApplicationID),
                RerResr = context.RerResrs.FirstOrDefault(c => c.ApplicationID == ApplicationID),
                ResearchStudyDetail = context.ResearchStudyDetails.FirstOrDefault(c => c.ApplicationID == ApplicationID),
                SubjectDefinedDetail = context.SubjectDefinedDetails.FirstOrDefault(c => c.ApplicationID == ApplicationID),
                RiskFactorDetail = context.RiskFactorDetails.FirstOrDefault(c => c.ApplicationID == ApplicationID),
                InformedConsent1 = context.InformedConsent1s.FirstOrDefault(c => c.ApplicationID == ApplicationID),
                InformedConsent2 = context.InformedConsent2s.FirstOrDefault(c => c.ApplicationID == ApplicationID),
                InformedConsent3 = context.InformedConsent3s.FirstOrDefault(c => c.ApplicationID == ApplicationID),
                PrincipalInvestigator = PI,
               

            };
            return View(viewModel);
        }

        private static List<UploadFiles> GetFiles(string id)
        {
            List<UploadFiles> files = new List<UploadFiles>();
            UploadFiles file = new UploadFiles();
            files = file.GetUploadedFiles(id);
            return files;
        }

        [HttpPost]
        public FileResult DownloadFile(string fileId)
        {
            byte[] bytes;
            string fileName, contentType;
            UploadFiles FileToDownload = new UploadFiles();
            FileToDownload = FileToDownload.GetFIleToDownload(fileId);
            fileName = FileToDownload.Name;
            contentType = FileToDownload.ContentType;
            bytes = FileToDownload.Data;
            return File(bytes, contentType, fileName);
        }

        //Get
        public ActionResult StandardDecisions(string id)
        {
            StandardAppDecisions standardApp = new StandardAppDecisions();

IRB web application/Views/IRBManagement/AssignApplication.cshtml
@model IRB_web_application.Models.ApplicationBasicDetail

@{
    ViewBag.Title = "AssignApplication";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AssignApplication</h2>

<div>
    <h4>ApplicationBasicDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SubmittedApplicationID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubmittedApplicationID)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.TypeOfApplication)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeOfApplication)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PISignedInitial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PISignedInitial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TitleOfResearch)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TitleOfResearch)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.ApplicationStartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationStartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateSubmitted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateSubmitted)
        </dd>

    </dl>
</div>
<form method="Post" action="/IRBManagement/AssignToSTaff">

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.DropDownList("Name", (SelectList)ViewBag.Name, "All IRB Members")
            <input type="submit" class="btn btn-default" value="View List" />
        </div>
    </div>
</form>

IRB web application/Views/IRBManagement/Details.cshtml
@model IRB_web_application.Models.ApplicationUser

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ApplicationUser</h4>
    <hr />
    <dl class="dl-horizontal">
       
        <dt>
            @Html.DisplayNameFor(model => model.UserPhoto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserPhoto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MiddleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StreetAddress1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StreetAddress1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StreetAddress2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StreetAddress2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CollegeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CollegeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.department)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResearchArea)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResearchArea)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Campus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Campus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsIRBChair)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsIRBChair)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

       
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "ListIRBMembers")
</p>

IRB web application/Views/IRBManagement/IRBApplicationsAssignedOrUndecided.cshtml
@model IEnumerable<IRB_web_application.Models.ApplicationBasicDetail>

@{
    ViewBag.Title = "IRBApplicationsAssignedOrUndecided";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>IRBApplicationsAssignedOrUndecided</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SubmittedApplicationID)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.TypeOfApplication)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.TitleOfResearch)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.ApplicationStartDate)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.DateSubmitted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AssignedStaff)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationState)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateStateUpdate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SubmittedApplicationID)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.TypeOfApplication)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.TitleOfResearch)
        </td>
      
        <td>
            @Html.DisplayFor(modelItem => item.ApplicationStartDate)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.DateSubmitted)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AssignedStaff)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApplicationState)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateStateUpdate)
        </td>
        <td>
            @Html.ActionLink("Review Application", "Edit", new { id=item.ApplicationID }) |
            @Html.ActionLink("Reassign to IRB Member", "Details", new { id=item.ApplicationID }) |
            @Html.ActionLink("Reassign to Applicant", "Delete", new { id=item.ApplicationID })
        </td>
    </tr>
}

</table>

IRB web application/Views/IRBManagement/IRBSumbittedApplication.cshtml
@model IEnumerable<IRB_web_application.Models.ApplicationBasicDetail>

@{
    ViewBag.Title = "IRBSumbittedApplication";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>IRBSumbittedApplication</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SubmittedApplicationID)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.TypeOfApplication)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.TitleOfResearch)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.DateSubmitted)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SubmittedApplicationID)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.TypeOfApplication)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.TitleOfResearch)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.DateSubmitted)
            </td>
            <td>
                @Html.ActionLink("Assign Application", "AssignApplication", new { id = item.ApplicationID })
                @*@Html.ActionLink("Details", "Details", new { id=item.ApplicationID }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.ApplicationID })*@
            </td>
        </tr>
    }

</table>

IRB web application/Views/IRBManagement/Index.cshtml
@model IRB_web_application.Models.ApplicationUser

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<div class="row">
    @if (User.Identity.IsAuthenticated)
    {

        if ((bool)Model.IsIRBChair)
        {
            <div class="col-md-4">
                <h2>New Submitted Application</h2>
                <p> @Html.ActionLink("UnAssigned Applications", "IRBSumbittedApplication", "IRBManagement", null, new { })</p>
            </div>

            <div class="col-md-4">
                <h2>Submitted Applications Already Assigned Or Yet to be Reviewed by Reviewer</h2>
                <p> @Html.ActionLink("Assigned Applications", "IRBApplicationsAssignedOrUndecided", "IRBManagement", null, new { })</p>
            </div>

            <div class="col-md-4">
                <h2>IRB Members</h2>
                <p> @Html.ActionLink("IRB Members", "ListIRBMembers", "IRBManagement", null, new { })</p>
            </div>

            <div class="col-md-4">
                <h2>All Applications</h2>
                <p> @Html.ActionLink("All Applications", "ListAllApplications", "IRBManagement", null, new { })</p>
            </div>
        }

        <div class="col-md-4">
            <h2>List of Standard Applications</h2>
            <p> @Html.ActionLink("Standard Applications", "ListIRBStandardApplication", "IRBManagement", null, new { })</p>
        </div>

        <div class="col-md-4">
            <h2>Applications Assigned to You</h2>
            <p> @Html.ActionLink("View Applications", "ListApplicationsAssignedToMember", "IRBManagement", null, new { })</p>
        </div>

    }



</div>

IRB web application/Views/IRBManagement/ListAllApplications.cshtml
@model IEnumerable<IRB_web_application.Models.ApplicationBasicDetail>

@{
    ViewBag.Title = "ListAllApplications";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ListAllApplications</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SubmittedApplicationID)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.TypeOfApplication)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.TitleOfResearch)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.DateSubmitted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AssignedStaff)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationState)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateStateUpdate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SubmittedApplicationID)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.TypeOfApplication)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.TitleOfResearch)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.DateSubmitted)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AssignedStaff)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApplicationState)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateStateUpdate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ApplicationID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ApplicationID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ApplicationID })
        </td>
    </tr>
}

</table>

IRB web application/Views/IRBManagement/ListApplicationsAssignedToMember.cshtml
@model IEnumerable<IRB_web_application.Models.ApplicationBasicDetail>

@{
    ViewBag.Title = "ListApplicationsAssignedToMember";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ListApplicationsAssignedToMember</h2>

<p>

</p>

<form method="Post" action="/IRBManagement/ListApplicationsAssignedToMember">

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.DropDownList("State", (SelectList)ViewBag.State, "Select Status")
            <input type="submit" class="btn btn-default" value="View List" />
        </div>
    </div>
</form>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SubmittedApplicationID)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.TypeOfApplication)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.TitleOfResearch)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.DateSubmitted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AssignedStaff)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationState)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateStateUpdate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SubmittedApplicationID)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.TypeOfApplication)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.TitleOfResearch)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.DateSubmitted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AssignedStaff)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationState)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateStateUpdate)
            </td>
            <td>
                @Html.ActionLink("Preview", "Preview", new { id = item.ApplicationID })
                


                @*@Html.ActionLink("Details", "Details", new { id=item.ApplicationID }) |
        @Html.ActionLink("Delete", "Delete", new { id=item.ApplicationID })*@
            </td>
        </tr>
    }

</table>

IRB web application/Views/IRBManagement/ListAssignedApplications.cshtml
@model IEnumerable<IRB_web_application.Models.ApplicationBasicDetail>

@{
    ViewBag.Title = "ListAssignedApplications";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ListAssignedApplications</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SubmittedApplicationID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TypeOfApplication)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.TitleOfResearch)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.ApplicationStartDate)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.DateSubmitted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AssignedStaff)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationState)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>

    <td>
        @Html.DisplayFor(modelItem => item.SubmittedApplicationID)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TypeOfApplication)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.TitleOfResearch)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.ApplicationStartDate)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.DateSubmitted)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.AssignedStaff)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ApplicationState)
    </td>
    <td>
        @Html.ActionLink("Review", "Edit", new { id = item.ApplicationID }) |
        @Html.ActionLink("Reassign to Applicant", "Details", new { id = item.ApplicationID }) |
        @Html.ActionLink("Reassign to another Member", "Delete", new { id = item.ApplicationID })
    </td>
</tr>
}

</table>