IRB web application/Models/ApplicationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IRB_web_application.Models
{
    public class ApplicationViewModel
    {
        ApplicationDbContext db = new ApplicationDbContext();
       
        public ApplicationUser PrincipalInvestigator { get; set; }
        public UploadFiles UploadFiles { get; set; }
        public ApplicationBasicDetail ApplicationBasicDetail { get; set; }
        public RerResr RerResr { get; set; }
        public ResearchStudyDetail ResearchStudyDetail { get; set; }
        public SubjectDefinedDetail SubjectDefinedDetail { get; set; }
        public RiskFactorDetail RiskFactorDetail { get; set; }
        public InformedConsent1 InformedConsent1 { get; set; }
        public InformedConsent2 InformedConsent2 { get; set; }
        public InformedConsent3 InformedConsent3 { get; set; }

       

    }
}

IRB web application/Models/DataHandlingDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace IRB_web_application.Models
{
    [Table("DataHandlingDetails")]
    public class DataHandlingDetail
    {
        [Key]
        public string ID { get; set; }

        //Foreign Key
        public string ApplicationID { get; set; }

        [ForeignKey("ApplicationID")]
        public virtual ApplicationBasicDetail Application { get; set; }

        [Display(Name = "Data Collection Method")]
        [StringLength(5000)]
        public string Data_Collection_Method { get; set; }

        [Display(Name = "Data Collection Method Other")]
        [StringLength(5000)]
        public string Data_Collection_Method_Other { get; set; }

        [Display(Name = "Data Collection Identifiers")]       
        public bool Data_Collect_Identi { get; set; }

        public string IsCollectIdentifiers
        {
            get
            {
                return (bool)this.Data_Collect_Identi ? "Yes" : "No";
            }
        }

        [Display(Name = "Data Retain Identifiers for Analysis")]
        public bool Data_Retain_Identi_Analysis { get; set; }

        public string IsCollectIdentifiersAnalysis
        {
            get
            {
                return (bool)this.Data_Retain_Identi_Analysis ? "Yes" : "No";
            }
        }

        [Display(Name = "Data Retain Identifiers for Reporting")]
        public bool Data_Retain_Identi_Reporting { get; set; }

        public string IsCollectIdentifiersReporting
        {
            get
            {
                return (bool)this.Data_Retain_Identi_Reporting ? "Yes" : "No";
            }
        }

        [Display(Name = "Research Disseminated to subjects")]
        [StringLength(5000)]
        public string Research_Dissem_Sub { get; set; }

        [Display(Name = "Storage Arrangement")]
        [StringLength(5000)]
        public string Storage_Arrangement { get; set; }

        [Display(Name = "Accounting Person")]
        [StringLength(5000)]
        public string Acc_Person { get; set; }

        [Display(Name = "Schedule and Method for De-Identification Of Data")]
        [StringLength(5000)]
        public string sch_mthd_deidenti_data { get; set; }

        [Display(Name = " Schedule And Methods For Long-Term Storage Of Raw Data.")]
        [StringLength(5000)]
        public string sch_mthd_raw_data { get; set; }

        [Display(Name = "Schedule And Methods For Eventual Destruction Of Data.")]
        [StringLength(5000)]
        public string sch_mthd_even_destruct { get; set; }

        [Display(Name = "Notes")]
        [StringLength(5000)]
        public string Notes { get; set; }

        public bool isCompleted { get; set; }

        public DateTime? ApplicationStartDate { get; set; }

        public DateTime? LastEditedDate { get; set; }

        ApplicationDbContext db = new ApplicationDbContext();
        public bool GetisCompleted(string id)
        {
            var query = from a in db.DataHandlingDetails
                        where a.ApplicationID.Equals(id)
                        select a.isCompleted;
            return query.FirstOrDefault();
        }

    }
}

IRB web application/Models/InformedConsent1.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace IRB_web_application.Models
{
    [Table("InformedConsent1")]
    public class InformedConsent1
    {
        [Key]
        public string ID { get; set; }

        //Foreign Key
        public string ApplicationID { get; set; }

        [ForeignKey("ApplicationID")]
        public virtual ApplicationBasicDetail Application { get; set; }

        [Display(Name = "Type of Consent")]
        [StringLength(5000)]
        public string TypeOfConsent { get; set; }

        [Display(Name = "Consent Form Distri")]
        [StringLength(5000)]
        public string ConsentFormDistri { get; set; }
        [Display(Name = "Notes")]
        [StringLength(5000)]
        public string Notes { get; set; }

        public bool IsSubInfWithdraw { get; set; }

        public string IsSubInfWithdrawString
        {
            get
            {
                return (bool)this.IsSubInfWithdraw ? "Yes" : "No";
            }
        }

        [Display(Name = "If No, Explain")]
        [StringLength(5000)]
        public string NoSubInfWithdraw { get; set; }


        public bool IsWrittenConsent { get; set; }

        public string IsWrittenConsentString
        {
            get
            {
                return (bool)this.IsWrittenConsent ? "Yes" : "No";
            }
        }

        [Display(Name = "If No, Explain")]
        [StringLength(5000)]
        public string NoWrittenConsent { get; set; }


        public bool IsOralConsent { get; set; }

        public string IsOralConsentString
        {
            get
            {
                return (bool)this.IsOralConsent ? "Yes" : "No";
            }
        }

        [Display(Name = "If Yes, Explain")]
        [StringLength(5000)]
        public string YesOralConsent { get; set; }

        public bool IsMinorParticipate { get; set; }

        public string IsMinorParticipateString
        {
            get
            {
                return (bool)this.IsMinorParticipate ? "Yes" : "No";
            }
        }

        [Display(Name = "If Yes, Explain")]
        [StringLength(5000)]
        public string YesMinorParticipate { get; set; }

        public bool IsMinorSubObtainAssent { get; set; }

        public string IsMinorSubObtainAssentString
        {
            get
            {
                return (bool)this.IsMinorSubObtainAssent ? "Yes" : "No";
            }
        }

        [Display(Name = "If Yes, Explain")]
        [StringLength(5000)]
        public string YesMinorSubObtainAssent { get; set; }

        public bool IsPrinciConsentWaive { get; set; }

        public string IsPrinciConsentWaiveString
        {
            get
            {
                return (bool)this.IsPrinciConsentWaive ? "Yes" : "No";
            }
        }

        [Display(Name = "If Yes, Explain")]
        [StringLength(5000)]
        public string YesPrinciConsentWaive { get; set; }

        public bool isCompleted { get; set; }



        public DateTime? LastEditedDate { get; set; }

        ApplicationDbContext db = new ApplicationDbContext();
        public bool GetisCompleted(string id)
        {
            var query = from a in db.InformedConsent1s
                        where a.ApplicationID.Equals(id)
                        select a.isCompleted;
            return query.FirstOrDefault();
        }
    }
}

IRB web application/Controllers/ApplicationController.cs
 using IRB_web_application.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IRB_web_application.Controllers
{
    public class ApplicationController : Controller
    {

        ApplicationDbContext context;
        private ApplicationUserManager _userManager;

        public ApplicationController()
        {
            context = new ApplicationDbContext();
        }
        public ApplicationController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ContinueApplication()
        {
            var user = User.Identity;

            var nonCompletedApplicationsList = context.ApplicationBasicDetails.ToList().Where(c => c.UserID == user.GetUserId() & c.isSubmitted == false);
            return View(nonCompletedApplicationsList);
        }

        // GET: ApplicationBasicDetail
        public ActionResult BasicDetail()
        {
            //ViewBag.PI = context.Users.Find(User.Identity.GetUserId());
            ViewBag.ApplicationTypeList = new SelectList(new List<string> { "Expedited", "Standard", "Exemption from Standard Review" });
            ApplicationBasicDetail applicationBasicDetail = new ApplicationBasicDetail();
            ApplicationUser PI = new ApplicationUser();
            PI = context.Users.Find(User.Identity.GetUserId());
            ViewBag.PIFullName = PI.FirstName + " "+ PI.MiddleName +" " + PI.LastName;
            ViewBag.PIMailingAddress = PI.StreetAddress1 +" "+ PI.City +", "+ PI.State +" "+ PI.Zip;
            ViewBag.PIPhoneNumber = PI.PhoneNumber;
            if (Session["ApplicationID"] != null)
            {
               
                applicationBasicDetail = context.ApplicationBasicDetails.Find(Session["ApplicationID"].ToString());
                

               

            }
            return View(applicationBasicDetail);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BasicDetail(ApplicationBasicDetail applicationdetail)
        {
            //try
            //{
            //    ViewBag.ApplicationTypeList = new SelectList(new List<string> { "Expedited", "Standard", "Exemption from Standard Review" });

                if (Session["ApplicationID"] != null & Session["UserID"] != null)
                {
                    applicationdetail.ApplicationID = Session["ApplicationID"].ToString();
                    applicationdetail.UserID = Session["UserID"].ToString();
                }
            ViewBag.PI = context.Users.Find(User.Identity.GetUserId());
            var existingApplication = await context.ApplicationBasicDetails.FindAsync(applicationdetail.ApplicationID);
                if (ModelState.IsValid)
                {
                    var user = User.Identity;

                    if (existingApplication != null)
                    {
                        // exists, Update Application
                        existingApplication.isGraduateStudent = applicationdetail.isGraduateStudent;
                        existingApplication.PISignedInitial = applicationdetail.PISignedInitial;
                        existingApplication.TitleOfResearch = applicationdetail.TitleOfResearch;
                        existingApplication.TypeOfApplication = applicationdetail.TypeOfApplication;
                        if (existingApplication.TypeOfApplication != "Standard")
                        {
                            if (existingApplication.TypeOfApplication == "Expedited" || existingApplication.TypeOfApplication == "Exemption from Standard Review")
                            {
                                existingApplication.isRerResr = true;// True means it is Request For Expedited Review Or Request for Exemption from standard Review
                                if(existingApplication.TypeOfApplication == "Expedited")
                                {
                                    ViewBag.SelectedApplication = "Expedited";
                                }else if(existingApplication.TypeOfApplication == "Exemption from Standard Review")
                                {
                                    ViewBag.SelectedApplication = "Exemption from Standard Review";
                                }
                            }
                            else 
                            {
                                existingApplication.isRerResr = false;
                            }
                        }
                        context.Entry(existingApplication).State = System.Data.Entity.EntityState.Modified;
                    }
                    else
                    {
                        //doesn't exist, save new Application
                        applicationdetail.ApplicationID = Guid.NewGuid().ToString() ;
                        applicationdetail.UserID = user.GetUserId();
                        if (applicationdetail.TypeOfApplication != "Standard")
                        {
                            if (applicationdetail.TypeOfApplication == "Expedited" || applicationdetail.TypeOfApplication == "Exemption from Standard Review")
                            {
                                applicationdetail.isRerResr = true;// True means it is Request For Expedited Review Or Request for Exemption from standard Review
                                
                                if (applicationdetail.TypeOfApplication == "Expedited")
                                {
                                    ViewBag.SelectedApplication = "Expedited";
                                }
                                else if (applicationdetail.TypeOfApplication == "Exemption from Standard Review")
                                {
                                    ViewBag.SelectedApplication = "Exemption from Standard Review";
                                }
                            }
                            else
                            {
                                applicationdetail.isRerResr = false;
                            }
                        }
                    if (User.IsInRole("Student"))
                    {
                        applicationdetail.isGraduateStudent = true;
                    }
                        //applicationdetail.ApplicationIDint = getNextApplicationID().AppID_int;
                        applicationdetail.LastEditedDate = DateTime.Now;
                        applicationdetail.ApplicationStartDate = DateTime.Now;
                        applicationdetail.isCompleted = true;
                        applicationdetail.ApplicationState = "Pending";
                        applicationdetail.DateStateUpdate = DateTime.Now;
                    context.ApplicationBasicDetails.Add(applicationdetail);
                        Session["ApplicationID"] = applicationdetail.ApplicationID;
                        Session["UserID"] = applicationdetail.UserID;

                    }


                    await context.SaveChangesAsync();

                }
            //}
            //catch (Exception e)
            //{

            //}
            if (applicationdetail.isGraduateStudent)
            {
                return RedirectToAction("FacultySponsor");
            }
           if (applicationdetail.TypeOfApplication == "Exemption from Standard Review") 
            {
                return RedirectToAction("ResrForm");
            }
            else if (applicationdetail.TypeOfApplication == "Expedited")
            {
                return RedirectToAction("RerForm");
            }
            else
            {
                return RedirectToAction("ResearchStudyDetail");
            }
            //return View();
        }
        

        public ActionResult ResearchStudyDetail()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "A new grant/contract", Value = "1" });
            items.Add(new SelectListItem { Text = "A dissertation or thesis", Value = "2" });
            items.Add(new SelectListItem { Text = "An independent study", Value = "3" });
            items.Add(new SelectListItem { Text = "A graduate research proposal", Value = "4" });
            items.Add(new SelectListItem { Text = "A class project", Value = "5" });
            items.Add(new SelectListItem { Text = "An undergraduate research proposal", Value = "6" });
            items.Add(new SelectListItem { Text = " A grant application", Value = "7" });

            //Need to Test This Action
            ResearchStudyDetail existingResearchStudyDetail = new ResearchStudyDetail();
            ResearchStudyDetailViewModel researchStudyDetailViewModel = new ResearchStudyDetailViewModel();
            researchStudyDetailViewModel.ResearchStudyProposal = items;
            ViewBag.PreviousUrl = System.Web.HttpContext.Current.Request.UrlReferrer.ToString();
            if (Session["ApplicationID"] != null)
            {
                string id = Session["ApplicationID"].ToString();
                existingResearchStudyDetail = context.ResearchStudyDetails.FirstOrDefault(c => c.ApplicationID == id);
                researchStudyDetailViewModel.ResearchStudyDetail = existingResearchStudyDetail;

            }
            return View(researchStudyDetailViewModel);

IRB web application/Views/Application/ApplicationTracker.cshtml
@model IRB_web_application.Models.ApplicationViewModel

<style>
    * {
        margin: 0;
        padding: 0;
        -moz-box-sizing: border-box;
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        font-size: 12px;
    }

    body {
        text-align: center;
        background-color: #34495e;
    }

    h1 {
        font-weight: 100;
        font-size: 32px;
        padding: 40px;
        color: #fff;
    }

    #breadcrumb {
        list-style: none;
        display: inline-block;
    }

        #breadcrumb .icon {
            font-size: 14px;
        }

        #breadcrumb li {
            float: left;
        }

            #breadcrumb li a {
                color: #FFF;
                display: block;
                background: #3498db;
                text-decoration: none;
                position: relative;
                height: 40px;
                line-height: 40px;
                padding: 0 10px 0 5px;
                text-align: center;
                margin-right: 23px;
            }

            #breadcrumb li:nth-child(even) a {
                background-color: #2980b9;
            }

                #breadcrumb li:nth-child(even) a:before {
                    border-color: #2980b9;
                    border-left-color: transparent;
                }

                #breadcrumb li:nth-child(even) a:after {
                    border-left-color: #2980b9;
                }

            #breadcrumb li:first-child a {
                padding-left: 15px;
                -moz-border-radius: 4px 0 0 4px;
                -webkit-border-radius: 4px;
                border-radius: 4px 0 0 4px;
            }

                #breadcrumb li:first-child a:before {
                    border: none;
                }

            #breadcrumb li:last-child a {
                padding-right: 15px;
                -moz-border-radius: 0 4px 4px 0;
                -webkit-border-radius: 0;
                border-radius: 0 4px 4px 0;
            }

                #breadcrumb li:last-child a:after {
                    border: none;
                }

            #breadcrumb li a:before, #breadcrumb li a:after {
                content: "";
                position: absolute;
                top: 0;
                border: 0 solid #3498db;
                border-width: 20px 10px;
                width: 0;
                height: 0;
            }

            #breadcrumb li a:before {
                left: -20px;
                border-left-color: transparent;
            }

            #breadcrumb li a:after {
                left: 100%;
                border-color: transparent;
                border-left-color: #3498db;
            }

            #breadcrumb li a:hover {
                background-color: #1abc9c;
            }

                #breadcrumb li a:hover:before {
                    border-color: #1abc9c;
                    border-left-color: transparent;
                }

                #breadcrumb li a:hover:after {
                    border-left-color: #1abc9c;
                }

            #breadcrumb li a:active {
                background-color: #16a085;
            }

                #breadcrumb li a:active:before {
                    border-color: #16a085;
                    border-left-color: transparent;
                }

                #breadcrumb li a:active:after {
                    border-left-color: #16a085;
                }
</style>



<ul id="breadcrumb">

    <li><a href="@Url.Action("Index","Application")"><span class="icon icon-home"> </span>Application</a></li>
    <li><a href="@Url.Action("BasicDetail","Application")"><span class="icon icon-beaker"> </span> Basic Details</a></li>


    @if (Model.ApplicationBasicDetail.isRerResr)
    {

        if (Model.ApplicationBasicDetail.TypeOfApplication == "Expedited")
        {
            <li><a href="@Url.Action("RerForm","Application")"><span class="icon icon-double-angle-right"></span> ReRForm</a></li>
        }
        else
        {
            <li><a href="@Url.Action("ResrForm","Application")"><span class="icon icon-rocket"> </span> ResrForm</a></li>
        }


    }

    @if (Model.ResearchStudyDetail != null)
    {
        if ((bool)Model.ResearchStudyDetail.isCompleted)
        {
            <li><a href="@Url.Action("ResearchStudyDetail", "Application")"><span class="icon icon-arrow-down"> </span> Research Study Detail</a></li>
        }
    }

    @if (Model.SubjectDefinedDetail != null)
    {
        if ((bool)Model.SubjectDefinedDetail.isCompleted)
        {
            <li><a href="@Url.Action("SubjectDefinedDetail", "Application")"><span class="icon icon-double-angle-right"></span> Subject Defined Detail</a></li>
        }
    }


    @if (Model.RiskFactorDetail != null)
    {
        if ((bool)Model.RiskFactorDetail.isCompleted)
        {
            <li><a href="@Url.Action("RiskFactorDetail", "Application")"><span class="icon icon-arrow-down"> </span> Risk Factor Detail</a></li>
        }
    }


    @if (Model.InformedConsent1 != null)
    {
        if ((bool)Model.InformedConsent1.isCompleted)
        {
            <li><a href="@Url.Action("InformedConsent1", "Application")"><span class="icon icon-rocket"> </span> Informed Consent 1 </a></li>
        }

    }

    @if (Model.InformedConsent2 != null)
    {
        if ((bool)Model.InformedConsent2.isCompleted)
        {
            <li><a href="@Url.Action("InformedConsent2", "Application")"><span class="icon icon-rocket"> </span> Informed Consent 2 </a></li>
        }
    }

    @if (Model.InformedConsent3 != null)
    {
        if ((bool)Model.InformedConsent3.isCompleted)
        {
            <li><a href="@Url.Action("InformedConsent3", "Application")"><span class="icon icon-rocket"> </span> Informed Consent 3 </a></li>
        }
    }
    @if (Model.UploadFiles != null)
    {
        if ((bool)Model.UploadFiles.isCompleted)
        {
            <li><a href="@Url.Action("UploadFiles", "Application")"><span class="icon icon-rocket"> </span> Upload Files  </a></li>
        }
    }
        <li><a href="@Url.Action("Preview","Application")"><span class="icon icon-rocket"> </span> Preview </a></li>

    </ul>

IRB web application/Views/Application/CollaborativeUsersManagement.cshtml
@model IEnumerable<IRB_web_application.Models.CollaborativeUsers>
@{
    ViewBag.Title = "CollaborativeUsersManagement";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CollaborativeUsersManagement</h2>

@using (Ajax.BeginForm("CollaborativeUsersManagement", new AjaxOptions
{
    HttpMethod = "Post",
    OnSuccess = "Loaded",

}))

{

    <div class="form-group">
        <div class="control-label col-md-2"> Email Address </div>
        <div class="col-md-10">
            <input type="text" class="form-control" name="EmailAddress" />
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-md-2"> Full Name </div>
        <div class="col-md-10">
            <input type="text" class="form-control" name="FullName" />
        </div>
    </div>

    <input type="submit" id="" value="Add User" />

}


@if (Model != null)
{
    foreach (var file in Model)
    {
        if (file.isRegistered == true)
        {
            <td>@ViewBag.ExistingUser.UserType</td>
           
        }

        <tr>

            <td>@file.FullName</td>
            <td>@file.EmailAddress</td>
            <td>@file.isRegistered</td>



            <td>
                @using (Ajax.BeginForm("DeleteCollabUser", new AjaxOptions
                {
                    HttpMethod = "Post",
                    OnSuccess = "Loaded",

                }))
                {
                    <input type="hidden" name="fileId" value=@file.ID />
                    <button type="submit" value="DeleteCollabUser">Delete</button>
                }
            </td>

        </tr>

    }
}


<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
<script type="text/javascript">
    function Loaded(result) {
        alert('result ' + result.Name);
    }
</script>

<div>
    @Html.ActionLink("Next", "Preview")
</div>

IRB web application/Views/Application/RerForm.cshtml
@model IRB_web_application.Models.RerResr

@{
    ViewBag.Title = "RerForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{ Html.Action("TrackApplication");}
<h2>RerForm</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Request For Expedited Review</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Que1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Que1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Que1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Que2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Que2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Que2, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

IRB web application/Views/Application/UploadFiles.cshtml
@model IRB_web_application.Models.UploadLinksViewModel

@{
    ViewBag.Title = "UploadFiles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{ Html.Action("TrackApplication");}
<h2>UploadFiles</h2>

@using (Html.BeginForm("UploadFiles", "Application", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="postedFile" />
    <input type="submit" id="btnUpload" value="Upload" />
}
@using (Html.BeginForm("DownloadFile", "Application", FormMethod.Post))
{
    <input type="hidden" id="hfFileId" name="FileId" />
    <input type="submit" id="btnDownload" value="Download" style="display:none" />
}
<hr />
<table cellpadding="0" cellspacing="0">
    <tr>

        <th style="width:120px">File Name</th>
        <th style="width:80px">Download</th>
        <th style="width:80px">Delete</th>
    </tr>

    @{ if (Model.uploadFiles.Count() > 0)
        {
            foreach (var file in Model.uploadFiles)
            {
                <tr>
                    <td>@file.Name</td>

                    <td>
                        @using (Ajax.BeginForm("DownloadFile", new AjaxOptions
                        {
                            HttpMethod = "Post",
                            OnSuccess = "Loaded",

                        }))
                        {
                            <input type="hidden" name="fileId" value=@file.ID />
                            <button type="submit" value="DownloadFile">Download</button>
                        }
                    </td>
                    <td>
                        @using (Ajax.BeginForm("DeleteFile", new AjaxOptions
                        {
                            HttpMethod = "Post",
                            OnSuccess = "Loaded",

                        }))
                        {
                            <input type="hidden" name="fileId" value=@file.ID />
                            <button type="submit" value="DeleteFile">Delete</button>
                        }
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="3">&nbsp;</td>
            </tr>
        }
    }
</table>



@using (Ajax.BeginForm("PostLink", new AjaxOptions
{
    HttpMethod = "Post",
    OnSuccess = "Loaded",

}))

{

    <div class="form-group">
        <div class="control-label col-md-2"> Name </div>
        <div class="col-md-10">
            <input type="text" class="form-control" name="Name" />
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-md-2"> url </div>
        <div class="col-md-10">
            <input type="text" class="form-control" name="Link" />
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-md-2"> Description </div>
        <div class="col-md-10">
            <input type="text" class="form-control" name="Description" />
        </div>
    </div>
    <input type="submit" id="btnDownload" value="PostLink" />

}





@if (Model.Hyperlinks != null)
{
    foreach (var file in Model.Hyperlinks)
    {
        <tr>
            <td><a href="http://@file.Link">@file.Name</a></td>
            <td>@file.Link</td>
            <td>@file.Description</td>

            <td>
                @using (Ajax.BeginForm("DeleteLink", new AjaxOptions
                {
                    HttpMethod = "Post",
                    OnSuccess = "Loaded",

                }))
                {
                    <input type="hidden" name="fileId" value=@file.ID />
                    <button type="submit" value="DeleteLink">Delete</button>
                }
            </td>

        </tr>

    }
}






<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
<script type="text/javascript">
    function Loaded(result) {
        alert('result ' + result.Name);
    }
</script>

<div>
    @Html.ActionLink("Next", "Preview")
</div>