IRB web application/Controllers/FacultyHubController.cs
using IRB_web_application.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IRB_web_application.Controllers
{
    public class FacultyHubController : Controller
    {

        ApplicationDbContext context;
        private ApplicationUserManager _userManager;
        
        public FacultyHubController()
        {
            context = new ApplicationDbContext();
        }
        public FacultyHubController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        // GET: FacultyHub
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult NewSponsorship()
        {
            var user = User.Identity;
            ApplicationBasicDetail application = new ApplicationBasicDetail();
            List<ApplicationViewModel> ApplicationList = application.GetApplicationListByFacultySponsorID(user.GetUserId(), "Pending");
            return View(ApplicationList);

        }

        public async Task<ActionResult> ApproveSponsor(string AppID)
        {
            ApplicationBasicDetail application = new ApplicationBasicDetail();
            application = await context.ApplicationBasicDetails.FindAsync(AppID);
            application.isFacultyApproved = true;
            context.Entry(application).State = System.Data.Entity.EntityState.Modified;
            await context.SaveChangesAsync();
            string to = "knigtdav001@gmail.com";
            string subject = "Approved";
            string body = "";
            await this.SendEmail(to, body, subject);
            return RedirectToAction("NewSponsorship");
        }

        public async Task SendEmail(string to, string body, string Subject)
        {
            GMailer mailer = new GMailer
            {
                ToEmail = to,
                Subject = Subject,
                Body = body,
                IsHtml = true
            };
            await mailer.Send();
        }


    }


}

IRB web application/Views/FacultyHub/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
<div class="row">

    <div class="col-lg-4 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>11</h3>

                <p>New Sponsorship Requests </p>
            </div>
            <div class="icon">
                <i class="fa fa-pencil"></i>
            </div>
            <p class="small-box-footer">@Html.ActionLink("New Sponsorship Request", "NewSponsorship", "FacultyHub", null, new { })&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></p>
        </div>
    </div>

    <div class="col-lg-4 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>11</h3>

                <p>Sponsored Applications</p>
            </div>
            <div class="icon">
                <i class="fa fa-pencil"></i>
            </div>
            <p class="small-box-footer"> @Html.ActionLink("Sponsored Applications", "SponsoredApplications", "FacultyHub", null, new { })&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></p>
        </div>
    </div>

   


</div>

IRB web application/Views/FacultyHub/NewSponsorship.cshtml
@model IEnumerable<IRB_web_application.Models.ApplicationViewModel>

@{
    ViewBag.Title = "NewSponsorship";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>NewSponsorship</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PrincipalInvestigator.FirstName)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.PrincipalInvestigator.LastName)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.PrincipalInvestigator.Email)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.PrincipalInvestigator.UserName)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.ApplicationBasicDetail.TitleOfResearch)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.ApplicationBasicDetail.TypeOfApplication)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.ApplicationBasicDetail.ApplicationStartDate)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>


    <td>
        @Html.DisplayFor(modelItem => item.PrincipalInvestigator.FirstName)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.PrincipalInvestigator.LastName)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.PrincipalInvestigator.Email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PrincipalInvestigator.UserName)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.ApplicationBasicDetail.TitleOfResearch)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ApplicationBasicDetail.TypeOfApplication)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ApplicationBasicDetail.ApplicationStartDate)
    </td>
    


    <td>
        @Html.ActionLink("Approve", "ApproveSponsor", new { AppID = item.ApplicationBasicDetail.ApplicationID }) |
        @Html.ActionLink("Details", "RejectSponsor", new { AppID = item.ApplicationBasicDetail.ApplicationID}) 
       
    </td>
</tr>
}

</table>